lis2ds12 self test - fix uninitialized array data
STMicroelectronics/STMems_Standard_C_drivers pull request #140
Opened 2021-09-08 20:22 UTC by andrewrt

**Please, start the title of the pull request with the part number involved** 
*ie: "lsm6dso: ..."*

---

### Device part numbers
list2ds12

Device list of the part numbers impacted by the bug. *(ie lis2mdl, lsm303agr)*

### Checklist

- [ ] improvement
- [ x] bug-fix
- [ ] other

### Description

Uninitialized arrays first accessed with += in self_test. 
Leads to outputs such as:
```
maes_st_off[0] = |-15.615999| ; 
maes_st_off[1] = |7725994429986635776.000000| ; 
maes_st_off[2] = |-1005.914368| ; 
``` 
etc. 

With this fix (array initializing) and re-testing, output updates to:
maes_st_off[0] = |-15.323201| ; 
maes_st_off[1] = |-23.472801| ; 
maes_st_off[2] = |-1006.597534| ;

2021-09-08 20:22 UTC, ST-dot-com commented
This pull request has been refused, the <a href='https://cla.st.com'>Contribution License Agreement</a> must be signed.

2021-09-08 20:23 UTC, andrewrt commented
License Agreement signed... re-open?

2021-09-09 07:09 UTC, avisconti commented
@andrewrt 

Thanks for ur contribution. It LGTM, but, even if in the past was not a must, from now on I would like to enforce the rule that a commit should have a title, a detailed message, and a Signed-off-by: with your name. Something like:

```
lis2ds12_STdC: fix uninitialized array data

<Explanation here>
#140

Signed-off-by: 
```

Please note #140 to create a link to this PR.
As you probably already know, you can add in .gitconfig your name and email as in this example:

git config --global user.name "David Developer"
git config --global user.email "david.developer@company.com"

Can you possibly repush the commit in this way?

Thanks,
Arm

2021-09-09 09:09 UTC, avisconti requested changes
Pls change the commit msg accordingly

2021-09-16 09:48 UTC, avisconti commented
@andrewrt 
If you can fix this commit as I requested would be better. Otherwise I'll accept as it is.

2021-09-16 16:08 UTC, avisconti commented
> @avisconti - updated. Let me know if this is all you want.

Yes, but put a space before #140, otherwise it seems that it does not create a link to this PR.
Thanks!

2021-09-17 16:32 UTC, andrewrt commented
> > @avisconti - updated. Let me know if this is all you want.
> 
> Yes, but put a space before #140, otherwise it seems that it does not create a link to this PR.
> Thanks!

done

2021-09-19 14:22 UTC, avisconti approved these changes
LGTM

2021-09-19 14:23 UTC, merged